import { BoardSpace, PlayerTokenInfo } from "./types";

export const BOARD_SPACES: BoardSpace[] = [
  // Bottom Row (0 -> 10)
  {
    id: 0,
    name: "Aarambh",
    hindi_name: "शुभ आरम्भ",
    type: "go",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Auspicious Beginning. Collect ₹2,000 salary upon passing or landing.",
    icon: "sparkles"
  },
  {
    id: 1,
    name: "Chandni Chowk",
    hindi_name: "चाँदनी चौक",
    type: "property",
    color_group: "Brown",
    price: 600,
    base_rent: 20,
    rent_1_house: 100,
    rent_2_house: 300,
    rent_3_house: 900,
    rent_4_house: 1600,
    rent_hotel: 2500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 300,
    city: "Old Delhi",
    state: "Delhi",
    description: "Mughal-era historic bazaar famous for spice markets and wholesale trade.",
    icon: "store"
  },
  {
    id: 2,
    name: "Panchayat",
    hindi_name: "पंचायत कल्याण",
    type: "panchayat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Panchayat & Community Welfare card.",
    icon: "users"
  },
  {
    id: 3,
    name: "Charminar Bazaar",
    hindi_name: "चारमीनार बाज़ार",
    type: "property",
    color_group: "Brown",
    price: 600,
    base_rent: 40,
    rent_1_house: 200,
    rent_2_house: 600,
    rent_3_house: 1800,
    rent_4_house: 3200,
    rent_hotel: 4500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 300,
    city: "Hyderabad",
    state: "Telangana",
    description: "Laad Bazaar pearl traders and historic monument surroundings.",
    icon: "landmark"
  },
  {
    id: 4,
    name: "Aaykar (Income Tax)",
    hindi_name: "आयकर",
    type: "tax",
    price: 2000,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Pay statutory Income Tax of ₹2,000 to the Bank.",
    icon: "receipt"
  },
  {
    id: 5,
    name: "Howrah Junction",
    hindi_name: "हावड़ा जंक्शन",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    city: "Kolkata",
    state: "West Bengal",
    description: "Eastern Railway gateway connecting millions daily over the Hooghly.",
    icon: "train"
  },
  {
    id: 6,
    name: "Promenade Beach",
    hindi_name: "प्रोमेनेड बीच",
    type: "property",
    color_group: "LightBlue",
    price: 1000,
    base_rent: 60,
    rent_1_house: 300,
    rent_2_house: 900,
    rent_3_house: 2700,
    rent_4_house: 4000,
    rent_hotel: 5500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 500,
    city: "Puducherry",
    state: "Puducherry",
    description: "Scenic French-colonial seafront promenade and boutique heritage villas.",
    icon: "palmtree"
  },
  {
    id: 7,
    name: "Kismat (Luck)",
    hindi_name: "किस्मत",
    type: "kismat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Kismat (Luck & Destiny) card.",
    icon: "clover"
  },
  {
    id: 8,
    name: "Calangute Strip",
    hindi_name: "कलंगूट बीच",
    type: "property",
    color_group: "LightBlue",
    price: 1000,
    base_rent: 60,
    rent_1_house: 300,
    rent_2_house: 900,
    rent_3_house: 2700,
    rent_4_house: 4000,
    rent_hotel: 5500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 500,
    city: "North Goa",
    state: "Goa",
    description: "High-energy beach tourist boulevard and resort strip.",
    icon: "sun"
  },
  {
    id: 9,
    name: "Marine Drive Kochi",
    hindi_name: "मरीन ड्राइव कोच्चि",
    type: "property",
    color_group: "LightBlue",
    price: 1200,
    base_rent: 80,
    rent_1_house: 400,
    rent_2_house: 1000,
    rent_3_house: 3000,
    rent_4_house: 4500,
    rent_hotel: 6000,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 600,
    city: "Kochi",
    state: "Kerala",
    description: "Picturesque backwaters waterfront promenade and commercial strip.",
    icon: "anchor"
  },
  // Left Column (10 -> 20)
  {
    id: 10,
    name: "Police Chowki",
    hindi_name: "पुलिस चौकी",
    type: "jail",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Detention Center / Hawalat. Just Visiting or Serving Bail Period.",
    icon: "shield-alert"
  },
  {
    id: 11,
    name: "MI Road (Pink City)",
    hindi_name: "एमआई रोड",
    type: "property",
    color_group: "Pink",
    price: 1400,
    base_rent: 100,
    rent_1_house: 500,
    rent_2_house: 1500,
    rent_3_house: 4500,
    rent_4_house: 6250,
    rent_hotel: 7500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 700,
    city: "Jaipur",
    state: "Rajasthan",
    description: "Mirza Ismail Road, Jaipur's regal handicraft, gems and emporium boulevard.",
    icon: "gem"
  },
  {
    id: 12,
    name: "National Power Grid",
    hindi_name: "ऊर्जा ग्रिड",
    type: "utility",
    price: 1500,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 750,
    description: "National Electricity Grid. Rent = 40x roll (1 owned) or 100x roll (both owned).",
    icon: "zap"
  },
  {
    id: 13,
    name: "Dashashwamedh Ghat",
    hindi_name: "दशाश्वमेध घाट",
    type: "property",
    color_group: "Pink",
    price: 1400,
    base_rent: 100,
    rent_1_house: 500,
    rent_2_house: 1500,
    rent_3_house: 4500,
    rent_4_house: 6250,
    rent_hotel: 7500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 700,
    city: "Varanasi",
    state: "Uttar Pradesh",
    description: "World's most iconic spiritual riverfront and heritage pilgrimage center.",
    icon: "flame"
  },
  {
    id: 14,
    name: "Mall Road Shimla",
    hindi_name: "माल रोड शिमला",
    type: "property",
    color_group: "Pink",
    price: 1600,
    base_rent: 120,
    rent_1_house: 600,
    rent_2_house: 1800,
    rent_3_house: 5000,
    rent_4_house: 7000,
    rent_hotel: 9000,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 800,
    city: "Shimla",
    state: "Himachal Pradesh",
    description: "Himalayan ridge pedestrian shopping promenade and colonial retreat.",
    icon: "mountain"
  },
  {
    id: 15,
    name: "CSMT Terminus",
    hindi_name: "सीएसएमटी मुंबई",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    city: "Mumbai",
    state: "Maharashtra",
    description: "UNESCO World Heritage Victorian Gothic landmark and Central Railway HQ.",
    icon: "train"
  },
  {
    id: 16,
    name: "FC Road (Deccan)",
    hindi_name: "एफसी रोड पुणे",
    type: "property",
    color_group: "Orange",
    price: 1800,
    base_rent: 140,
    rent_1_house: 700,
    rent_2_house: 2000,
    rent_3_house: 5500,
    rent_4_house: 7500,
    rent_hotel: 9500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 900,
    city: "Pune",
    state: "Maharashtra",
    description: "Fergusson College Road, vibrant youth cafe and educational-commercial strip.",
    icon: "coffee"
  },
  {
    id: 17,
    name: "Panchayat",
    hindi_name: "पंचायत कल्याण",
    type: "panchayat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Panchayat & Community Welfare card.",
    icon: "users"
  },
  {
    id: 18,
    name: "CG Road",
    hindi_name: "सीजी रोड अहमदाबाद",
    type: "property",
    color_group: "Orange",
    price: 1800,
    base_rent: 140,
    rent_1_house: 700,
    rent_2_house: 2000,
    rent_3_house: 5500,
    rent_4_house: 7500,
    rent_hotel: 9500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 900,
    city: "Ahmedabad",
    state: "Gujarat",
    description: "Chimanlal Girdharlal Road, prime retail and enterprise avenue.",
    icon: "briefcase"
  },
  {
    id: 19,
    name: "Sector 17 Plaza",
    hindi_name: "सेक्टर 17 प्लाज़ा",
    type: "property",
    color_group: "Orange",
    price: 2000,
    base_rent: 160,
    rent_1_house: 800,
    rent_2_house: 2200,
    rent_3_house: 6000,
    rent_4_house: 8000,
    rent_hotel: 10000,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 1000,
    city: "Chandigarh",
    state: "Chandigarh",
    description: "Le Corbusier planned pedestrian shopping hub with open courtyards.",
    icon: "building"
  },
  // Top Row (20 -> 30)
  {
    id: 20,
    name: "Vishram Sthal",
    hindi_name: "विश्राम स्थल",
    type: "free_parking",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Free Resting Zone (Yatri Niwas). Relax and plan your investments.",
    icon: "tent"
  },
  {
    id: 21,
    name: "Park Street",
    hindi_name: "पार्क स्ट्रीट",
    type: "property",
    color_group: "Red",
    price: 2200,
    base_rent: 180,
    rent_1_house: 900,
    rent_2_house: 2500,
    rent_3_house: 7000,
    rent_4_house: 8750,
    rent_hotel: 10500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1100,
    city: "Kolkata",
    state: "West Bengal",
    description: "The cultural, culinary, and nightlife high-street of Kolkata.",
    icon: "music"
  },
  {
    id: 22,
    name: "Kismat (Luck)",
    hindi_name: "किस्मत",
    type: "kismat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Kismat (Luck & Destiny) card.",
    icon: "clover"
  },
  {
    id: 23,
    name: "HITEC City Towers",
    hindi_name: "हाईटेक सिटी",
    type: "property",
    color_group: "Red",
    price: 2200,
    base_rent: 180,
    rent_1_house: 900,
    rent_2_house: 2500,
    rent_3_house: 7000,
    rent_4_house: 8750,
    rent_hotel: 10500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1100,
    city: "Hyderabad",
    state: "Telangana",
    description: "Cyberabad flagship technology park housing global software giants.",
    icon: "cpu"
  },
  {
    id: 24,
    name: "Brigade & MG Road",
    hindi_name: "ब्रिगेड रोड",
    type: "property",
    color_group: "Red",
    price: 2400,
    base_rent: 200,
    rent_1_house: 1000,
    rent_2_house: 3000,
    rent_3_house: 7500,
    rent_4_house: 9250,
    rent_hotel: 11000,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1200,
    city: "Bengaluru",
    state: "Karnataka",
    description: "Silicon Plateau's bustling commercial core and tech headquarters.",
    icon: "laptop"
  },
  {
    id: 25,
    name: "New Delhi Junction",
    hindi_name: "नई दिल्ली रेलवे",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    city: "New Delhi",
    state: "Delhi",
    description: "Northern Railway mega-terminus handling over 500,000 travelers daily.",
    icon: "train"
  },
  {
    id: 26,
    name: "T. Nagar & Anna Salai",
    hindi_name: "टी. नगर चेन्नई",
    type: "property",
    color_group: "Yellow",
    price: 2600,
    base_rent: 220,
    rent_1_house: 1100,
    rent_2_house: 3300,
    rent_3_house: 8000,
    rent_4_house: 9750,
    rent_hotel: 11500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1300,
    city: "Chennai",
    state: "Tamil Nadu",
    description: "India's largest retail silk and gold jewelry shopping district.",
    icon: "shopping-bag"
  },
  {
    id: 27,
    name: "Golf Course Road",
    hindi_name: "गोल्फ कोर्स रोड",
    type: "property",
    color_group: "Yellow",
    price: 2600,
    base_rent: 220,
    rent_1_house: 1100,
    rent_2_house: 3300,
    rent_3_house: 8000,
    rent_4_house: 9750,
    rent_hotel: 11500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1300,
    city: "Gurugram",
    state: "Haryana",
    description: "Millennium City's ultra-luxury condominium and corporate glass tower corridor.",
    icon: "building-2"
  },
  {
    id: 28,
    name: "Jal Jeevan Board",
    hindi_name: "जल जीवन बोर्ड",
    type: "utility",
    price: 1500,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 750,
    description: "National Water Infrastructure. Rent = 40x roll (1 owned) or 100x roll (both owned).",
    icon: "droplets"
  },
  {
    id: 29,
    name: "GS Road Dispur",
    hindi_name: "जीएस रोड गुवाहाटी",
    type: "property",
    color_group: "Yellow",
    price: 2800,
    base_rent: 240,
    rent_1_house: 1200,
    rent_2_house: 3600,
    rent_3_house: 8500,
    rent_4_house: 10250,
    rent_hotel: 12000,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1400,
    city: "Guwahati",
    state: "Assam",
    description: "Northeast India's premier commercial and hospitality expressway.",
    icon: "map-pin"
  },
  // Right Column (30 -> 39)
  {
    id: 30,
    name: "Nyayalay Saman",
    hindi_name: "न्यायालय समन",
    type: "go_to_jail",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Court summons issued! Advance directly to Police Chowki without collecting salary.",
    icon: "gavel"
  },
  {
    id: 31,
    name: "Connaught Place",
    hindi_name: "कनॉट प्लेस",
    type: "property",
    color_group: "Green",
    price: 3000,
    base_rent: 260,
    rent_1_house: 1300,
    rent_2_house: 3900,
    rent_3_house: 9000,
    rent_4_house: 11000,
    rent_hotel: 12750,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1500,
    city: "New Delhi",
    state: "Delhi",
    description: "Iconic circular Georgian colonial colonnade and corporate nerve center.",
    icon: "compass"
  },
  {
    id: 32,
    name: "Bandra-Kurla BKC",
    hindi_name: "बांद्रा-कुर्ला BKC",
    type: "property",
    color_group: "Green",
    price: 3000,
    base_rent: 260,
    rent_1_house: 1300,
    rent_2_house: 3900,
    rent_3_house: 9000,
    rent_4_house: 11000,
    rent_hotel: 12750,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1500,
    city: "Mumbai",
    state: "Maharashtra",
    description: "India's highest valued central financial district and corporate headquarters.",
    icon: "landmark"
  },
  {
    id: 33,
    name: "Panchayat",
    hindi_name: "पंचायत कल्याण",
    type: "panchayat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Panchayat & Community Welfare card.",
    icon: "users"
  },
  {
    id: 34,
    name: "Lutyens' Zone",
    hindi_name: "लुटियंस दिल्ली",
    type: "property",
    color_group: "Green",
    price: 3200,
    base_rent: 280,
    rent_1_house: 1500,
    rent_2_house: 4500,
    rent_3_house: 10000,
    rent_4_house: 12000,
    rent_hotel: 14000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1600,
    city: "New Delhi",
    state: "Delhi",
    description: "The nation's most elite diplomatic power corridors and sprawling estate grounds.",
    icon: "crown"
  },
  {
    id: 35,
    name: "Chennai Central",
    hindi_name: "चेन्नई सेंट्रल",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    city: "Chennai",
    state: "Tamil Nadu",
    description: "Southern Railway's majestic crimson Romanesque transit nexus.",
    icon: "train"
  },
  {
    id: 36,
    name: "Kismat (Luck)",
    hindi_name: "किस्मत",
    type: "kismat",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Kismat (Luck & Destiny) card.",
    icon: "clover"
  },
  {
    id: 37,
    name: "Altamount Road",
    hindi_name: "अल्टामाउंट रोड",
    type: "property",
    color_group: "DarkBlue",
    price: 3500,
    base_rent: 350,
    rent_1_house: 1750,
    rent_2_house: 5000,
    rent_3_house: 11000,
    rent_4_house: 13000,
    rent_hotel: 15000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1750,
    city: "Mumbai",
    state: "Maharashtra",
    description: "Billionaires' Boulevard on Cumballa Hill, home to India's wealthiest magnates.",
    icon: "diamond"
  },
  {
    id: 38,
    name: "GST Luxury Cess",
    hindi_name: "विलासिता उपकर",
    type: "tax",
    price: 1000,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Pay statutory Luxury Goods & High-Wealth Cess of ₹1,000 to the Bank.",
    icon: "badge-dollar-sign"
  },
  {
    id: 39,
    name: "Marine Drive",
    hindi_name: "मरीन ड्राइव मुंबई",
    type: "property",
    color_group: "DarkBlue",
    price: 4000,
    base_rent: 500,
    rent_1_house: 2000,
    rent_2_house: 6000,
    rent_3_house: 14000,
    rent_4_house: 17000,
    rent_hotel: 20000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 2000,
    city: "Mumbai",
    state: "Maharashtra",
    description: "The iconic Queen's Necklace waterfront arc and crown jewel of Indian real estate.",
    icon: "sparkle"
  }
];

export const PLAYER_TOKENS: PlayerTokenInfo[] = [
  { id: "auto_rickshaw", name: "Auto-Rickshaw", hindi: "ऑटो-रिक्शा", finish: "Antique Brass", icon: "🛺", color: "#F59E0B" },
  { id: "royal_elephant", name: "Royal Elephant", hindi: "शाही हाथी", finish: "Rose Copper", icon: "🐘", color: "#EC4899" },
  { id: "cricket_bat", name: "Cricket Bat", hindi: "क्रिकेट बल्ला", finish: "Sterling Silver", icon: "🏏", color: "#3B82F6" },
  { id: "cutting_chai", name: "Cutting Chai", hindi: "कटिंग चाय", finish: "Stainless Steel", icon: "☕", color: "#D97706" },
  { id: "locomotive", name: "WAP-7 Engine", hindi: "रेल इंजन", finish: "Gunmetal", icon: "🚂", color: "#6B7280" },
  { id: "scooter", name: "Bajaj Chetak", hindi: "चेतक स्कूटर", finish: "Matte Nickel", icon: "🛵", color: "#10B981" },
  { id: "lotus", name: "National Lotus", hindi: "कमल पुष्प", finish: "24K Gold", icon: "🪷", color: "#FBBF24" },
  { id: "clapperboard", name: "Bollywood Reel", hindi: "सिनेमा क्लैपर", finish: "Black Chrome", icon: "🎬", color: "#8B5CF6" },
];

export const COLOR_GROUP_STYLES: Record<string, { bg: string; border: string; text: string; label: string }> = {
  Brown: { bg: "bg-amber-900", border: "border-amber-700", text: "text-amber-100", label: "Heritage Terracotta" },
  LightBlue: { bg: "bg-sky-500", border: "border-sky-400", text: "text-sky-950", label: "Coastal Cyan" },
  Pink: { bg: "bg-pink-600", border: "border-pink-400", text: "text-pink-50", label: "Royal Magenta" },
  Orange: { bg: "bg-orange-500", border: "border-orange-400", text: "text-orange-950", label: "Saffron Sunset" },
  Red: { bg: "bg-red-600", border: "border-red-400", text: "text-red-50", label: "Crimson Festive" },
  Yellow: { bg: "bg-yellow-400", border: "border-yellow-300", text: "text-yellow-950", label: "Golden Ochre" },
  Green: { bg: "bg-emerald-600", border: "border-emerald-400", text: "text-emerald-50", label: "Emerald Capital" },
  DarkBlue: { bg: "bg-indigo-900", border: "border-indigo-600", text: "text-indigo-50", label: "Royal Indigo" },
};
