import { BoardSpace, PlayerTokenInfo } from "./types";

export const BOARD_SPACES: BoardSpace[] = [
  // Bottom Row (0 -> 10)
  {
    id: 0,
    name: "START / GO",
    monument: "National Gateway",
    city: "National",
    state: "India",
    type: "go",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Collect ₹2,000 salary as you pass or land.",
    icon: "sparkles"
  },
  {
    id: 1,
    name: "Chandni Chowk",
    monument: "Red Fort & Bazaar",
    city: "Old Delhi",
    state: "Delhi",
    type: "property",
    color_group: "Brown",
    price: 600,
    base_rent: 20,
    rent_1_house: 100,
    rent_2_house: 300,
    rent_3_house: 900,
    rent_4_house: 1600,
    rent_hotel: 2500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 300,
    description: "Historic Mughal bazaar famous for spice markets and wholesale trade.",
    icon: "landmark"
  },
  {
    id: 2,
    name: "Community Chest",
    monument: "Community Fund",
    city: "National",
    state: "India",
    type: "community",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Community Chest Card.",
    icon: "users"
  },
  {
    id: 3,
    name: "Charminar Bazaar",
    monument: "Charminar & Laad Bazaar",
    city: "Hyderabad",
    state: "Telangana",
    type: "property",
    color_group: "Brown",
    price: 600,
    base_rent: 40,
    rent_1_house: 200,
    rent_2_house: 600,
    rent_3_house: 1800,
    rent_4_house: 3200,
    rent_hotel: 4500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 300,
    description: "Iconic 16th-century four-minaret monument and famous pearl markets.",
    icon: "monument"
  },
  {
    id: 4,
    name: "Income Tax",
    monument: "Direct Tax Office",
    city: "Central",
    state: "Revenue",
    type: "tax",
    price: 2000,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Pay statutory Income Tax of ₹2,000 to the Bank.",
    icon: "receipt"
  },
  {
    id: 5,
    name: "Howrah Junction",
    monument: "Howrah Bridge & Station",
    city: "Kolkata",
    state: "West Bengal",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    description: "Eastern Railway landmark and one of the world's busiest historic stations.",
    icon: "train"
  },
  {
    id: 6,
    name: "Promenade Beach",
    monument: "French War Memorial",
    city: "Puducherry",
    state: "Puducherry",
    type: "property",
    color_group: "LightBlue",
    price: 1000,
    base_rent: 60,
    rent_1_house: 300,
    rent_2_house: 900,
    rent_3_house: 2700,
    rent_4_house: 4000,
    rent_hotel: 5500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 500,
    description: "Scenic French-colonial seafront promenade and boutique heritage villas.",
    icon: "palmtree"
  },
  {
    id: 7,
    name: "Chance",
    monument: "Fortune Wheel",
    city: "National",
    state: "India",
    type: "chance",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Chance Card.",
    icon: "clover"
  },
  {
    id: 8,
    name: "Calangute Strip",
    monument: "Aguada Fort & Beach",
    city: "North Goa",
    state: "Goa",
    type: "property",
    color_group: "LightBlue",
    price: 1000,
    base_rent: 60,
    rent_1_house: 300,
    rent_2_house: 900,
    rent_3_house: 2700,
    rent_4_house: 4000,
    rent_hotel: 5500,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 500,
    description: "High-energy coastal tourist boulevard and 17th-century Portuguese fortress.",
    icon: "sun"
  },
  {
    id: 9,
    name: "Marine Drive Kochi",
    monument: "Chinese Fishing Nets & Fort",
    city: "Kochi",
    state: "Kerala",
    type: "property",
    color_group: "LightBlue",
    price: 1200,
    base_rent: 80,
    rent_1_house: 400,
    rent_2_house: 1000,
    rent_3_house: 3000,
    rent_4_house: 4500,
    rent_hotel: 6000,
    house_cost: 500,
    hotel_cost: 500,
    mortgage_value: 600,
    description: "Picturesque backwaters waterfront promenade and commercial spice harbor.",
    icon: "anchor"
  },
  // Left Column (10 -> 20)
  {
    id: 10,
    name: "In Jail / Visiting",
    monument: "Detention Center",
    city: "Judicial",
    state: "Jurisdiction",
    type: "jail",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Detention Center. Just Visiting is safe; prisoners pay ₹500 or roll doubles.",
    icon: "shield-alert"
  },
  {
    id: 11,
    name: "MI Road (Pink City)",
    monument: "Hawa Mahal & City Palace",
    city: "Jaipur",
    state: "Rajasthan",
    type: "property",
    color_group: "Pink",
    price: 1400,
    base_rent: 100,
    rent_1_house: 500,
    rent_2_house: 1500,
    rent_3_house: 4500,
    rent_4_house: 6250,
    rent_hotel: 7500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 700,
    description: "Mirza Ismail Road, Jaipur's regal handicraft, gems and emporium avenue.",
    icon: "gem"
  },
  {
    id: 12,
    name: "National Power Grid",
    monument: "PowerGrid & NTPC",
    city: "National",
    state: "Infrastructure",
    type: "utility",
    price: 1500,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 750,
    description: "National Electricity Transmission Grid. Rent = 40x roll (1 owned) or 100x roll (both owned).",
    icon: "zap"
  },
  {
    id: 13,
    name: "Dashashwamedh Ghat",
    monument: "Kashi Vishwanath Corridor",
    city: "Varanasi",
    state: "Uttar Pradesh",
    type: "property",
    color_group: "Pink",
    price: 1400,
    base_rent: 100,
    rent_1_house: 500,
    rent_2_house: 1500,
    rent_3_house: 4500,
    rent_4_house: 6250,
    rent_hotel: 7500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 700,
    description: "World's most iconic spiritual riverfront and heritage pilgrimage center.",
    icon: "flame"
  },
  {
    id: 14,
    name: "Mall Road",
    monument: "The Ridge & Viceregal Lodge",
    city: "Shimla",
    state: "Himachal Pradesh",
    type: "property",
    color_group: "Pink",
    price: 1600,
    base_rent: 120,
    rent_1_house: 600,
    rent_2_house: 1800,
    rent_3_house: 5000,
    rent_4_house: 7000,
    rent_hotel: 9000,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 800,
    description: "Himalayan ridge pedestrian shopping promenade and colonial retreat.",
    icon: "mountain"
  },
  {
    id: 15,
    name: "CSMT Terminus",
    monument: "Victoria Gothic Landmark",
    city: "Mumbai",
    state: "Maharashtra",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    description: "UNESCO World Heritage Victorian Gothic landmark and Central Railway HQ.",
    icon: "train"
  },
  {
    id: 16,
    name: "FC Road (Deccan)",
    monument: "Shaniwar Wada Fort",
    city: "Pune",
    state: "Maharashtra",
    type: "property",
    color_group: "Orange",
    price: 1800,
    base_rent: 140,
    rent_1_house: 700,
    rent_2_house: 2000,
    rent_3_house: 5500,
    rent_4_house: 7500,
    rent_hotel: 9500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 900,
    description: "Fergusson College Road, vibrant youth cafe and educational-commercial strip.",
    icon: "coffee"
  },
  {
    id: 17,
    name: "Community Chest",
    monument: "Community Fund",
    city: "National",
    state: "India",
    type: "community",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Community Chest Card.",
    icon: "users"
  },
  {
    id: 18,
    name: "CG Road",
    monument: "Sabarmati Riverfront",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "property",
    color_group: "Orange",
    price: 1800,
    base_rent: 140,
    rent_1_house: 700,
    rent_2_house: 2000,
    rent_3_house: 5500,
    rent_4_house: 7500,
    rent_hotel: 9500,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 900,
    description: "Chimanlal Girdharlal Road, prime retail, enterprise, and jewelry avenue.",
    icon: "briefcase"
  },
  {
    id: 19,
    name: "Sector 17 Plaza",
    monument: "Capitol Complex & Rock Garden",
    city: "Chandigarh",
    state: "Chandigarh",
    type: "property",
    color_group: "Orange",
    price: 2000,
    base_rent: 160,
    rent_1_house: 800,
    rent_2_house: 2200,
    rent_3_house: 6000,
    rent_4_house: 8000,
    rent_hotel: 10000,
    house_cost: 1000,
    hotel_cost: 1000,
    mortgage_value: 1000,
    description: "Le Corbusier planned pedestrian shopping hub with open courtyards.",
    icon: "building"
  },
  // Top Row (20 -> 30)
  {
    id: 20,
    name: "Free Parking",
    monument: "Transit Rest Zone",
    city: "Safe",
    state: "Zone",
    type: "free_parking",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Free Resting Zone. Relax and plan your investments.",
    icon: "tent"
  },
  {
    id: 21,
    name: "Park Street",
    monument: "Victoria Memorial & Park St",
    city: "Kolkata",
    state: "West Bengal",
    type: "property",
    color_group: "Red",
    price: 2200,
    base_rent: 180,
    rent_1_house: 900,
    rent_2_house: 2500,
    rent_3_house: 7000,
    rent_4_house: 8750,
    rent_hotel: 10500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1100,
    description: "The cultural, culinary, and nightlife high-street of Kolkata.",
    icon: "music"
  },
  {
    id: 22,
    name: "Chance",
    monument: "Fortune Wheel",
    city: "National",
    state: "India",
    type: "chance",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Chance Card.",
    icon: "clover"
  },
  {
    id: 23,
    name: "HITEC City",
    monument: "Cyber Towers & Golconda",
    city: "Hyderabad",
    state: "Telangana",
    type: "property",
    color_group: "Red",
    price: 2200,
    base_rent: 180,
    rent_1_house: 900,
    rent_2_house: 2500,
    rent_3_house: 7000,
    rent_4_house: 8750,
    rent_hotel: 10500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1100,
    description: "Cyberabad flagship technology park housing leading global software corporations.",
    icon: "cpu"
  },
  {
    id: 24,
    name: "Brigade & MG Road",
    monument: "Vidhana Soudha & Cubbon Park",
    city: "Bengaluru",
    state: "Karnataka",
    type: "property",
    color_group: "Red",
    price: 2400,
    base_rent: 200,
    rent_1_house: 1000,
    rent_2_house: 3000,
    rent_3_house: 7500,
    rent_4_house: 9250,
    rent_hotel: 11000,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1200,
    description: "Silicon Plateau's bustling commercial core and tech innovation district.",
    icon: "laptop"
  },
  {
    id: 25,
    name: "New Delhi Junction",
    monument: "India Gate & Rail Terminal",
    city: "New Delhi",
    state: "Delhi",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    description: "Northern Railway mega-terminus handling over 500,000 travelers daily.",
    icon: "train"
  },
  {
    id: 26,
    name: "T. Nagar & Anna Salai",
    monument: "Ripon Building & Marina Beach",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "property",
    color_group: "Yellow",
    price: 2600,
    base_rent: 220,
    rent_1_house: 1100,
    rent_2_house: 3300,
    rent_3_house: 8000,
    rent_4_house: 9750,
    rent_hotel: 11500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1300,
    description: "India's largest retail silk and gold jewelry shopping district.",
    icon: "shopping-bag"
  },
  {
    id: 27,
    name: "Golf Course Road",
    monument: "Cyber Hub & Horizon Center",
    city: "Gurugram",
    state: "Haryana",
    type: "property",
    color_group: "Yellow",
    price: 2600,
    base_rent: 220,
    rent_1_house: 1100,
    rent_2_house: 3300,
    rent_3_house: 8000,
    rent_4_house: 9750,
    rent_hotel: 11500,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1300,
    description: "Millennium City's ultra-luxury condominium and corporate glass tower corridor.",
    icon: "building-2"
  },
  {
    id: 28,
    name: "Water Authority",
    monument: "National Water Infrastructure",
    city: "National",
    state: "Infrastructure",
    type: "utility",
    price: 1500,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 750,
    description: "National Water Infrastructure. Rent = 40x roll (1 owned) or 100x roll (both owned).",
    icon: "droplets"
  },
  {
    id: 29,
    name: "GS Road Dispur",
    monument: "Kamakhya Temple & Guwahati",
    city: "Guwahati",
    state: "Assam",
    type: "property",
    color_group: "Yellow",
    price: 2800,
    base_rent: 240,
    rent_1_house: 1200,
    rent_2_house: 3600,
    rent_3_house: 8500,
    rent_4_house: 10250,
    rent_hotel: 12000,
    house_cost: 1500,
    hotel_cost: 1500,
    mortgage_value: 1400,
    description: "Northeast India's premier commercial and hospitality expressway.",
    icon: "map-pin"
  },
  // Right Column (30 -> 39)
  {
    id: 30,
    name: "Go To Jail",
    monument: "Judicial Arrest Warrant",
    city: "Legal",
    state: "Jurisdiction",
    type: "go_to_jail",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Advance directly to Jail. Do not pass GO, do not collect ₹2,000.",
    icon: "gavel"
  },
  {
    id: 31,
    name: "Connaught Place",
    monument: "India Gate & CP Colonnade",
    city: "New Delhi",
    state: "Delhi",
    type: "property",
    color_group: "Green",
    price: 3000,
    base_rent: 260,
    rent_1_house: 1300,
    rent_2_house: 3900,
    rent_3_house: 9000,
    rent_4_house: 11000,
    rent_hotel: 12750,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1500,
    description: "Iconic circular Georgian colonial colonnade and corporate nerve center.",
    icon: "compass"
  },
  {
    id: 32,
    name: "Bandra-Kurla BKC",
    monument: "Bandra-Worli Sea Link",
    city: "Mumbai",
    state: "Maharashtra",
    type: "property",
    color_group: "Green",
    price: 3000,
    base_rent: 260,
    rent_1_house: 1300,
    rent_2_house: 3900,
    rent_3_house: 9000,
    rent_4_house: 11000,
    rent_hotel: 12750,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1500,
    description: "India's highest valued central financial district and corporate headquarters.",
    icon: "landmark"
  },
  {
    id: 33,
    name: "Community Chest",
    monument: "Community Fund",
    city: "National",
    state: "India",
    type: "community",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Community Chest Card.",
    icon: "users"
  },
  {
    id: 34,
    name: "Lutyens' Zone",
    monument: "Rashtrapati Bhavan & Qutub",
    city: "New Delhi",
    state: "Delhi",
    type: "property",
    color_group: "Green",
    price: 3200,
    base_rent: 280,
    rent_1_house: 1500,
    rent_2_house: 4500,
    rent_3_house: 10000,
    rent_4_house: 12000,
    rent_hotel: 14000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1600,
    description: "The nation's most elite diplomatic power corridors and sprawling estate grounds.",
    icon: "crown"
  },
  {
    id: 35,
    name: "Chennai Central",
    monument: "Chennai Central Heritage Station",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "transport",
    price: 2000,
    base_rent: 250,
    rent_1_house: 500,
    rent_2_house: 1000,
    rent_3_house: 2000,
    rent_4_house: 2000,
    rent_hotel: 2000,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 1000,
    description: "Southern Railway's majestic crimson Romanesque transit nexus.",
    icon: "train"
  },
  {
    id: 36,
    name: "Chance",
    monument: "Fortune Wheel",
    city: "National",
    state: "India",
    type: "chance",
    price: 0,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Draw a Chance Card.",
    icon: "clover"
  },
  {
    id: 37,
    name: "Altamount Road",
    monument: "Gateway of India & Antilia",
    city: "Mumbai",
    state: "Maharashtra",
    type: "property",
    color_group: "DarkBlue",
    price: 3500,
    base_rent: 350,
    rent_1_house: 1750,
    rent_2_house: 5000,
    rent_3_house: 11000,
    rent_4_house: 13000,
    rent_hotel: 15000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 1750,
    description: "Billionaires' Boulevard on Cumballa Hill, home to India's wealthiest magnates.",
    icon: "diamond"
  },
  {
    id: 38,
    name: "Luxury Tax",
    monument: "High-Wealth Assessment",
    city: "Treasury",
    state: "Taxation",
    type: "tax",
    price: 1000,
    base_rent: 0,
    rent_1_house: 0,
    rent_2_house: 0,
    rent_3_house: 0,
    rent_4_house: 0,
    rent_hotel: 0,
    house_cost: 0,
    hotel_cost: 0,
    mortgage_value: 0,
    description: "Pay statutory Luxury Tax of ₹1,000 to the Bank.",
    icon: "badge-dollar-sign"
  },
  {
    id: 39,
    name: "Marine Drive",
    monument: "Queen's Necklace Promenade",
    city: "Mumbai",
    state: "Maharashtra",
    type: "property",
    color_group: "DarkBlue",
    price: 4000,
    base_rent: 500,
    rent_1_house: 2000,
    rent_2_house: 6000,
    rent_3_house: 14000,
    rent_4_house: 17000,
    rent_hotel: 20000,
    house_cost: 2000,
    hotel_cost: 2000,
    mortgage_value: 2000,
    description: "The iconic Queen's Necklace waterfront arc and crown jewel of Indian real estate.",
    icon: "sparkle"
  }
];

export const PLAYER_TOKENS: PlayerTokenInfo[] = [
  { id: "auto_rickshaw", name: "Auto-Rickshaw", finish: "Antique Brass", icon: "🛺", color: "#F59E0B" },
  { id: "royal_elephant", name: "Royal Elephant", finish: "Rose Copper", icon: "🐘", color: "#EC4899" },
  { id: "cricket_bat", name: "Cricket Bat & Ball", finish: "Sterling Silver", icon: "🏏", color: "#3B82F6" },
  { id: "cutting_chai", name: "Chai Cup", finish: "Stainless Steel", icon: "☕", color: "#D97706" },
  { id: "locomotive", name: "Steam Locomotive", finish: "Gunmetal", icon: "🚂", color: "#6B7280" },
  { id: "scooter", name: "Vintage Scooter", finish: "Matte Nickel", icon: "🛵", color: "#10B981" },
  { id: "lotus", name: "National Lotus", finish: "24K Gold", icon: "🪷", color: "#FBBF24" },
  { id: "clapperboard", name: "Film Clapper", finish: "Black Chrome", icon: "🎬", color: "#8B5CF6" },
];

export const COLOR_GROUP_STYLES: Record<string, { bg: string; border: string; text: string; label: string }> = {
  Brown: { bg: "bg-amber-900", border: "border-amber-700", text: "text-amber-100", label: "Brown Group" },
  LightBlue: { bg: "bg-sky-500", border: "border-sky-400", text: "text-sky-950", label: "Light Blue Group" },
  Pink: { bg: "bg-pink-600", border: "border-pink-400", text: "text-pink-50", label: "Pink Group" },
  Orange: { bg: "bg-orange-500", border: "border-orange-400", text: "text-orange-950", label: "Orange Group" },
  Red: { bg: "bg-red-600", border: "border-red-400", text: "text-red-50", label: "Red Group" },
  Yellow: { bg: "bg-yellow-400", border: "border-yellow-300", text: "text-yellow-950", label: "Yellow Group" },
  Green: { bg: "bg-emerald-600", border: "border-emerald-400", text: "text-emerald-50", label: "Green Group" },
  DarkBlue: { bg: "bg-indigo-900", border: "border-indigo-600", text: "text-indigo-50", label: "Dark Blue Group" },
};
